"""Update string fields

Revision ID: 2295deac99ab
Revises: 121f1bb2e0e7
Create Date: 2025-07-10 11:30:06.871801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2295deac99ab'
down_revision = '121f1bb2e0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
